name: Reindex TypeSense

on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_pages:
    name:  Reindex TypeSense
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
      TYPESENSE_HOST: typesense.acdh-dev.oeaw.ac.at
      TYPESENSE_PORT: 443
      TYPESENSE_PROTOCOL: https
      TYPESENSE_API_KEY: ${{secrets.TYPESENSE_API_KEY}}
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
         python-version: '3.10'
    - name: Setup Java / Ant
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Install Python libraries
      run: |
        pip install -U pip
        pip install -r build_app/python/requirements.txt
    - name: Fetch data
      run: |
        chmod +x build_app/shell/* build_app/python/*
        ./build_app/shell/fetch_data.sh
    - name: Install Saxon, Ant and Fundament
      run: |
        apt-get update && apt-get install ant -y --no-install-recommend
        ./build_app/shell/script.sh
    - name: preprocess
      run: |
        ant -f build_app/ant/preprocess.xml
    - name: add attributes and denormalize indices
      run: |
        ./build_app/shell/attributes.sh
        ./build_app/shell/denormalize.sh
    - name: Build
      run: |
        ant -f build_app/ant/build.xml
        ant -f build_app/ant/fixtures.xml
    - name: Build Typesense Index
      run: |
        python build_app/python/make_ts_index.py
