name: XML-TEI to LaTeX Transformation

on:
  # push:
  #  branches:
  #    - main
  workflow_dispatch: # Allows manual triggering

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build_app/python/requirements.txt

    - name: Transform XML-TEI to LaTeX
      run: |
        mkdir -p data/tex  # Create the output folder
        for file in data/editions/*.xml; do
          echo "Processing $file..."
          build_app/python/tei2latex.py "$file" "data/tex/$(basename "${file%.xml}.tex")"
        done

    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex texlive-latex-recommended texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

    - name: Compile LaTeX to PDF
      run: |
        mkdir -p idata/pdf  # Create the folder for PDF files
        for file in data/tex/*.tex; do
          echo "Compiling $file..."
          xelalatex -output-directory=data/pdf "$file"
        done

    # Step 7: Commit and push PDFs
    - name: Commit and push PDF files
      run: |
        git add data/pdf/*.pdf
        git commit -m "Generated PDFs from LaTeX files"
        git push
