name: XML-TEI to LaTeX Transformation

on:
  # push:
  #  branches:
  #    - main
  workflow_dispatch: # Allows manual triggering

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Fetch data
      run: |
        ./build_app/shell/fetch_data.sh
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build_app/python/requirements.txt

    - name: Transform XML-TEI to LaTeX
      run: |
        mkdir -p data/{critics,traktat,vms}/{tex,pdf} html/pdf
        folders=("data/critics" "data/traktat" "data/vms")
        for folder in "${folders[@]}" ; do
          find "$folder/editions" -type f -name "*.xml" | while read filename; do
            echo "Transforming $filename"
            build_app/python/xml2latex.py "$filename" "$folder/tex/$(basename ${file%.xml}.tex)"
          done
        done
    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex texlive-latex-recommended texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

    - name: Compile LaTeX to PDF
      run: |
        folders=("data/critics" "data/traktat" "data/vms")
        for folder in "${folders[@]}"; do
          find "$folder/tex" -type f -name "*.tex" | while read filename; do
            echo "Compiling $filename"
            xelatex -interaction=nonstopmode -output-directory="pdf/html" "$filename"
          done
        done
    - name: Commit and push PDF files
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Export and Transformation done
